// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUubFfzK1CADpvr7zSBzfteZsocWLBp2A',
    appId: '1:769448200311:web:2472278f1d050ac6371e72',
    messagingSenderId: '769448200311',
    projectId: 'assinmentlogin-ff0dc',
    authDomain: 'assinmentlogin-ff0dc.firebaseapp.com',
    storageBucket: 'assinmentlogin-ff0dc.firebasestorage.app',
    measurementId: 'G-VK20XGP9B1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3S9l4ORce0_VtS-0J8nnWBtpLN0SahqE',
    appId: '1:769448200311:android:226697ae27165c74371e72',
    messagingSenderId: '769448200311',
    projectId: 'assinmentlogin-ff0dc',
    storageBucket: 'assinmentlogin-ff0dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFD0jJrjraExn3v8bajrYmJneyMrHwKb4',
    appId: '1:769448200311:ios:5df47fb8cef06821371e72',
    messagingSenderId: '769448200311',
    projectId: 'assinmentlogin-ff0dc',
    storageBucket: 'assinmentlogin-ff0dc.firebasestorage.app',
    iosBundleId: 'com.example.assinment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFD0jJrjraExn3v8bajrYmJneyMrHwKb4',
    appId: '1:769448200311:ios:5df47fb8cef06821371e72',
    messagingSenderId: '769448200311',
    projectId: 'assinmentlogin-ff0dc',
    storageBucket: 'assinmentlogin-ff0dc.firebasestorage.app',
    iosBundleId: 'com.example.assinment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUubFfzK1CADpvr7zSBzfteZsocWLBp2A',
    appId: '1:769448200311:web:332f481ea4068cc6371e72',
    messagingSenderId: '769448200311',
    projectId: 'assinmentlogin-ff0dc',
    authDomain: 'assinmentlogin-ff0dc.firebaseapp.com',
    storageBucket: 'assinmentlogin-ff0dc.firebasestorage.app',
    measurementId: 'G-C5FFFJ40VX',
  );
}
